// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: chat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketMessage_Type int32

const (
	WebSocketMessage_UNKNOWN      WebSocketMessage_Type = 0
	WebSocketMessage_AUTH         WebSocketMessage_Type = 1
	WebSocketMessage_TEXT_MESSAGE WebSocketMessage_Type = 2
	WebSocketMessage_ACK          WebSocketMessage_Type = 3
	WebSocketMessage_TYPING       WebSocketMessage_Type = 4
	WebSocketMessage_ERROR        WebSocketMessage_Type = 5
)

// Enum value maps for WebSocketMessage_Type.
var (
	WebSocketMessage_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "AUTH",
		2: "TEXT_MESSAGE",
		3: "ACK",
		4: "TYPING",
		5: "ERROR",
	}
	WebSocketMessage_Type_value = map[string]int32{
		"UNKNOWN":      0,
		"AUTH":         1,
		"TEXT_MESSAGE": 2,
		"ACK":          3,
		"TYPING":       4,
		"ERROR":        5,
	}
)

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}

func (x WebSocketMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebSocketMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (WebSocketMessage_Type) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x WebSocketMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebSocketMessage_Type.Descriptor instead.
func (WebSocketMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0, 0}
}

type WebSocketMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      WebSocketMessage_Type  `protobuf:"varint,1,opt,name=type,proto3,enum=securemesh.WebSocketMessage_Type" json:"type,omitempty"`
	Id        string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Payload   []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// === НОВЫЕ ПОЛЯ ===
	SenderId      string `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`          // Кто отправил (UUID)
	RecipientId   string `protobuf:"bytes,6,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"` // Кому отправить (UUID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketMessage) GetType() WebSocketMessage_Type {
	if x != nil {
		return x.Type
	}
	return WebSocketMessage_UNKNOWN
}

func (x *WebSocketMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebSocketMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WebSocketMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *WebSocketMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

type AckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckPayload) Reset() {
	*x = AckPayload{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckPayload) ProtoMessage() {}

func (x *AckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckPayload.ProtoReflect.Descriptor instead.
func (*AckPayload) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *AckPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AckPayload) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\n" +
	"securemesh\"\xa2\x02\n" +
	"\x10WebSocketMessage\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.securemesh.WebSocketMessage.TypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x06 \x01(\tR\vrecipientId\"O\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04AUTH\x10\x01\x12\x10\n" +
	"\fTEXT_MESSAGE\x10\x02\x12\a\n" +
	"\x03ACK\x10\x03\x12\n" +
	"\n" +
	"\x06TYPING\x10\x04\x12\t\n" +
	"\x05ERROR\x10\x05\"H\n" +
	"\n" +
	"AckPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderIdB7Z5github.com/yerkebulanrai/securemesh/backend/pkg/protob\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_proto_goTypes = []any{
	(WebSocketMessage_Type)(0), // 0: securemesh.WebSocketMessage.Type
	(*WebSocketMessage)(nil),   // 1: securemesh.WebSocketMessage
	(*AckPayload)(nil),         // 2: securemesh.AckPayload
}
var file_chat_proto_depIdxs = []int32{
	0, // 0: securemesh.WebSocketMessage.type:type_name -> securemesh.WebSocketMessage.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
